language: java
jdk:
  - oraclejdk7
  - openjdk6
install: mvn -q install -DskipTests=true
script: mvn -e test
# whitelist
branches:
  only:
    - master

notifications:
  recipients:
    - elaatifi@gmail.com
    - matt.deboer@gmail.com
  email:
    on_success: always
    on_failure: always